# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-15 18:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0006_place_load_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_price', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
