# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-15 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_unitprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitprice',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
