# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20190116_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='status',
            field=models.BooleanField(choices=[(True, 'Auto'), (False, 'Manual')], default=False),
        ),
    ]
