# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-13 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_place_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='serial',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='load',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
