# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-13 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20190413_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='serial',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
