# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-25 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_auto_20190420_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='typeLoad',
            field=models.PositiveIntegerField(choices=[(0, 'Normal'), (1, 'Secure')], default=0),
        ),
    ]
