# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-30 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_load_typeload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='typeLoad',
            field=models.PositiveIntegerField(choices=[(0, 'Normal'), (1, 'Secure'), (2, 'Levels')], default=0),
        ),
    ]
