# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20181202_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='device_type',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
