# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-24 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_remove_device_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
        migrations.AddField(
            model_name='device',
            name='unit',
            field=models.CharField(default=0, max_length=50, verbose_name='Measure unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='device_measure_data',
            field=models.ManyToManyField(blank=True, null=True, to='devices.DataMeasure'),
        ),
        migrations.DeleteModel(
            name='DeviceType',
        ),
    ]
