# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-03 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_device_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datameasure',
            name='value',
            field=models.IntegerField(),
        ),
    ]
