# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-12 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_auto_20190104_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='unit',
            field=models.CharField(choices=[('m3', 'm3'), ('tds', 'tds')], max_length=50, verbose_name='Measure unit'),
        ),
    ]
