# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-12 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_auto_20190112_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datameasure',
            name='receive_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
